apiVersion: v1
kind: Pod
spec:
  containers:
    - image: us-west1-docker.pkg.dev/dremio-1093/dockerhub/alpine:3.23.2
      imagePullPolicy: Always
      name: agent
      command: ["tail", "-f", "/dev/null"]
      workingDir: /workspace
      resources:
        limits:
          cpu: 3.5
          memory: 4G
        requests:
          cpu: 3.5
          memory: 4G
  serviceAccountName: support-tools-sa
  restartPolicy: Never
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
