#!/bin/sh

# script/lint: Run gofmt and golangci-lint run

set -e

cd "$(dirname "$0")/.."

go fmt ./...

echo "executing golangci-lint run"
golangci-lint run --sort-results -E revive,gofmt,govet,errcheck,gosec,wastedassign,usestdlibvars,errorlint

echo "executing license-header-checker"
license-header-checker license_header.txt . go
