#!/bin/sh

# script/test: Run all tests

#set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

./script/clean
./script/build-musl


arch=$(uname -m)
if test "$arch" = "x86_64"; then
    CC=x86_64-linux-musl-cc CGO_ENABLED=1 go test --ldflags '-linkmode external -extldflags "-static"' -race -coverpkg=./... -coverprofile=covprofile ./...
else
    CC=aarch64-linux-musl-cc CGO_ENABLED=1 go test --ldflags '-linkmode external -extldflags "-static"' -race -coverpkg=./... -coverprofile=covprofile ./...
fi