apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ddc-collect
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumes
  - limitranges
  - resoucesquotas
  - services
  - endpoints
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
