apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ddc-collect
subjects:
- kind: ServiceAccount
  name: ddc-collect
  namespace: default
roleRef:
  kind: Role
  name: ddc-collect 
  apiGroup: rbac.authorization.k8s.io
