name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  os_matrix:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    build:
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: CI
        run:  ./script/cibuild
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
